version: 2
jobs:
  build_latest:
    docker:
      - image: circleci/golang:1.16
    working_directory: ~/zdamegzzawodowybackend
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      # build the application image
      - run: docker build -t $DOCKER_LOGIN/zdam-egzamin-zawodowy-backend:latest .
      # deploy the image
      - run: docker push $DOCKER_LOGIN/zdam-egzamin-zawodowy-backend:latest
  build_version:
    docker:
      - image: circleci/golang:1.16
    working_directory: ~/zdamegzzawodowybackend
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      # build the application image
      - run: docker build -t $DOCKER_LOGIN/zdam-egzamin-zawodowy-backend:$(echo $CIRCLE_TAG | sed -r 's/^.{1}//') .
      # deploy the image
      - run: docker push $DOCKER_LOGIN/zdam-egzamin-zawodowy-backend:$(echo $CIRCLE_TAG | sed -r 's/^.{1}//')
workflows:
  version: 2
  deploy_latest:
    jobs:
      - build_latest:
          context: Zdam-Egzamin-Zawodowy
          filters:
            branches:
              only:
                - master
  deploy_version:
    jobs:
      - build_version:
          context: Zdam-Egzamin-Zawodowy
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
